version: '3'
services:
  abb-discord-bot:
    image: lakker/abb-discord-bot:latest
    container_name: abb-discord-bot
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      wget https://github.com/jamcalli/ABB-Discord-Bot/releases/download/Release/docker-compose.yml
wget -O .env https://github.com/jamcalli/ABB-Discord-Bot/releases/download/Release/example.env
